<?php

include_once("Services/Init/classes/class.ilInitialisation.php");

/**
 * Class srInitialisation
 *
 * @author Fabian Schmid <fs@studer-raimann.ch>
 */
class srInitialisation extends ilInitialisation {

	/**
	 * @var string
	 */
	protected static $context;


	/**
	 * @param ilContext
	 */
	public static function setContext($context) {
		srContext::init($context);
		self::$context = $context;
	}

	public static function initILIAS() {
		parent::initILIAS(); // TODO: Change the autogenerated stub
		$tpl = new ilTemplate("tpl.main.html", true, true, 'Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting');
		$tpl->addCss('./templates/default/delos.css');
		$tpl->addBlockFile("CONTENT", "content", "tpl.main_voter.html", 'Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting');
		$tpl->setVariable('BASE', '/'); // FSX TODO set to real root

		self::initGlobal("tpl", $tpl);

		// always load jQuery
		include_once("./Services/jQuery/classes/class.iljQueryUtil.php");
		iljQueryUtil::initjQuery();

		// always load ui framework
		include_once("./Services/UICore/classes/class.ilUIFramework.php");
		ilUIFramework::init();
	}
}
